export const GET_POST_LIST = 'GET_POST_LIST';
export const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS';
export const GET_POST_LIST_FAILED = 'GET_POST_LIST_FAILED';

export const GET_LIST_BY_TOPIC = 'GET_LIST_BY_TOPIC';
export const GET_LIST_BY_TOPIC_SUCCESS = 'GET_LIST_BY_TOPIC_SUCCESS';
export const GET_LIST_BY_TOPIC_FAILED = 'GET_LIST_BY_TOPIC_FAILED';
